apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: headscale
  name: headscale
  namespace: headscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headscale
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: headscale
    spec:
      containers:
        - args:
            - serve
          image: ghcr.io/juanfont/headscale:0.29.2
          livenessProbe:
            exec:
              command:
                - headscale
                - health
          name: headscale
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 3478
              protocol: UDP
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /etc/headscale
              name: headscale-configmap
              readOnly: true
            - mountPath: /var/lib/headscale
              name: headscale-claim
            - mountPath: /var/run/headscale
              name: headscale-tmpfs0
      restartPolicy: Always
      volumes:
        - configMap:
            name: headscale-configmap
          name: headscale-configmap
        - name: headscale-claim
          persistentVolumeClaim:
            claimName: headscale-claim
        - emptyDir:
            medium: Memory
          name: headscale-tmpfs0
