apiVersion: v1
kind: Service
metadata:
  labels:
    app: headscale
  name: headscale
  namespace: headscale
spec:
  type: LoadBalancer
  selector:
    app: headscale
  ports:
    - name: 'http'
      port: 8080
      targetPort: 8080
    - name: "https"
      port: 443
      targetPort: 443
      protocol: TCP
    - name: "stun"
      port: 3478
      targetPort: 3478
      protocol: UDP
