grafana:
  enabled: true

  persistence:
    enabled: true
    storageClassName: longhorn-ssd
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.lan
    tls: []

  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki.monitoring.svc.cluster.lan:3100
      access: proxy
      isDefault: false
    - name: Tempo
      type: tempo
      url: http://tempo.monitoring.svc.cluster.lan:3100
      access: proxy
      isDefault: false

  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
