apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    providers:
      longhorn:
        url: https://longhorn.lan
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - icon: si-github
              href: https://github.com/mferrie
  services.yaml: |
    - Infrastructure:
        - Longhorn:
            icon: si-longhorn
            href: http://longhorn.lan/
            description: Distributed block storage
            siteMonitor: http://longhorn-frontend.longhorn-system.svc.cluster.local
    - Apps:
        - Immich:
            icon: si-immich
            href: http://immich.lan/
            description: Photo storage server
            siteMonitor: http://immich-server.immich.svc.cluster.local:2283
        - LGTM Stack:
            icon: si-grafana
            href: http://grafana.lan/
            description: Cluster metrics
            siteMonitor: http://prometheus-grafana.monitoring.svc.cluster.local
        - Netbird:
            icon: sh-netbird-light
            href: https://netbird.mafmanhomelab.dedyn.io/
            description: Mesh VPN
            siteMonitor: https://netbird.mafmanhomelab.dedyn.io/
        - NextCloud:
            icon: si-nextcloud
            href: http://cloud.lan/
            description: NAS server
            siteMonitor: http://nextcloud.nextcloud.svc.cluster.local:8080
        - PiHole:
            icon: si-pihole
            href: http://pihole.lan/admin
            description: DNS server / sinkhole filter
            siteMonitor: http://pihole-web.pihole.svc.cluster.local
        - Mealie:
            icon: si-mealie
            href: http://mealie.lan
            description: Recipe manager
            siteMonitor: http://mealie.mealie.svc.cluster.local:9000
        - ForgeJo:
            icon: si-forgejo
            href: http://git.lan
            description: Git server
            siteMonitor: http://forgejo-http.forgejo.svc.cluster.local:3000
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
  proxmox.yaml: ""
