apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: default
  settings.yaml: |
    providers:
      longhorn:
        url: https://longhorn.lan
    title: Local Cloud
    description: Making Big Tech obsolete
    background:
        image: https://eol.jsc.nasa.gov/DatabaseImages/EO/highres/ISS056/ISS056-E-77502.JPG
        blur: "sm"
        saturate: 100
        brightness: 100
        opacity: 50
    cardBlur: xs
    theme: dark
    color: "neutral"
    opacity: 75
    headerStyle: boxed
    statusStyle: 'dot'
    layout:
        Networking:
            style: row
            columns: 4
        Media:
            style: row
            columns: 4
        Utilities:
            style: row
            columns: 4

  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Project:
        - CodeBerg:
            - icon: sh-codeberg
              href: https://codeberg.org/kaizenOramara_97
        - GitLab:
            - icon: sh-gitlab
              href: https://gitlab.com/mferrie
    - Socials:
        - Mastodon:
            - icon: https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/mastodon-icon.png
              href: https://mastodon.social/@ferriematthew
        - BlueSky:
            - icon: https://logowik.com/content/uploads/images/bluesky-social5027.logowik.com.webp
              href: https://bsky.app/profile/ferriematthew.bsky.social
        - MakerTube:
            - icon: sh-peertube
              href: https://makertube.net/a/kaizen_oramara_97/video-channels
        - PixelFed:
            - icon: sh-pixelfed
              href: https://pixelfed.social/kaizenOramara_97
        - Lemmy:
            - icon: sh-lemmy
              href: https://lemmy.ml/u/kaizenOramara_97
        - Stoat:
            - icon: sh-stoat
              href: https://stoat.chat
  services.yaml: |
    - Infrastructure:
        - Longhorn:
            icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/rancher-longhorn.png
            href: http://longhorn.lan/
            description: Distributed block storage
            siteMonitor: http://longhorn-frontend.longhorn-system.svc.cluster.local
            statusStyle: 'dot'
        - LGTM Stack:
            icon: sh-grafana
            href: http://grafana.lan/
            description: Cluster metrics
            siteMonitor: http://grafana.lgtm.svc.cluster.local:3000
            statusStyle: 'dot'
        - SearXNG:
            icon: sh-searxng
            href: https://search.lan/
            description: Private search engine
            siteMonitor: http://searxng-service.searxng.svc.cluster.local:8080
            statusStyle: 'dot'
    - Networking:
        - PiHole:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/pi-hole.png
            href: http://pihole.lan/admin
            description: DNS server / sinkhole filter
            siteMonitor: http://pihole-web.pihole.svc.cluster.local
            statusStyle: 'dot'
        - Netbird:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/netbird.png
            href: https://netbird.mafmanhomelab.dedyn.io/
            description: Mesh VPN
            siteMonitor: https://netbird.mafmanhomelab.dedyn.io/
            statusStyle: 'dot'
    - Media:
        - Immich:
            icon: sh-immich
            href: http://immich.lan/
            description: Photo storage server
            siteMonitor: http://immich-server.immich.svc.cluster.local:2283
            statusStyle: 'dot'
        - NextCloud:
            icon: sh-nextcloud
            href: http://cloud.lan/
            description: NAS server
            siteMonitor: http://nextcloud.nextcloud.svc.cluster.local:8080
            statusStyle: 'dot'
        - Mealie:
            icon: sh-mealie
            href: http://mealie.lan
            description: Recipe manager
            siteMonitor: http://mealie.mealie.svc.cluster.local:9000
            statusStyle: 'dot'
        - ForgeJo:
            icon: sh-forgejo
            href: http://git.lan
            description: Git server
            siteMonitor: http://forgejo-http.forgejo.svc.cluster.local:3000
            statusStyle: 'dot'
  widgets.yaml: |
    - search:
        provider: custom
        url: https://search.lan/search?q=
        target: _blank
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "Cluster"
          expanded: true
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
          expanded: true
    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: true
    - resources:
        backend: resources
        expanded: true
        network: default
        cputemp: true
        uptime: true
        refresh: 1000
  docker.yaml: ""
  proxmox.yaml: ""
