---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-key
  namespace: homepage
spec:
  encryptedData:
    token: AgCkbW7WlYYUujxjKkc1Uhlu9CZRtgxjvL8zxi7QjDDBJ3rcQa1Zfg1DdWMRK1vvsYKMP8QueAwEL7PpyBbmYsFNPQV40Hfl2vTESZXC5pJb4qnJviOZSwVof/aEHiyk6zaN6hZLwjhGGYDQ5fzfrwGiYBLrXaBsJliuBz6VblN28qHlCkA/Kj2wlW8i2/T7/QKmXE1cB9175RktU3tmxXBIbUAsBJ7Ms0BAO5FavnxVWhh8ejzmZ3QR5qfd9cUuOV82LhwmODkQZjlXZ+fveYi1Vj/6ylpPhx+CJpJhiFKZay1yVGBaf0gHM/214tU8hrnRn43IrXgdjgHyTPzyIt6oJ060Wism0F0yo9D19eC7EdymQY7OuBZUsU5mzyQx7pOLnrZpVdJHDwpm5PyowedT2lu9o1Egd7ryVQOBLmNCsfruzvoKQoUn73oAlQUaEYjA20kKFPJnlfJ09NTpQhIb8GJi/Pr43AJi1q0drsHu1HrTxRS7WqHWsvtGC46UWdntfHOiS2QLiTPXOMbkDxG1K3LB8hK3HNjspukuKe+I2oPk91fV9Uc2svYT23jTeEYYfPrTw5Or3ZaC3bWYgXApY1vwZzsJxqlg2r5SmT5fbsrNIefg35NsQGsRdkOrqyZgDNxsLxrsI5fl/aLgCgajnawP+framArPvO14nyG0x3/ieUuhcii9VMkJONZuTsVQhFs2w4IpSZutFg94KYc7W8VBnF45OnwQQUcUVvcQwR2MFVCMlQZ1
  template:
    metadata:
      name: forgejo-key
      namespace: homepage
