---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-key
  namespace: homepage
spec:
  encryptedData:
    key: AgAlzFIiQ4yY64sLKL+3j/LYj2aA3CPrRfvIHCi7lQuy64rizSU+T1wL5Sbi24ktotVMAen/i6/XNDR59WpyLs1MACKPqWdicN9Smtxh3GYR4QQAufoMjFaTu248XJD8eqZjmTJFyi1XmkXn+r4vIrq68dRNh45CH+ir8unTJlX1BFPjn1A0D6e4/0Lck70zYUeAg7tfmUfEAdvfbZOXmiVfPAaMDBIEhtdb6eT2fiZKpTy0UWN2wnhNhi7ZgVPdDSnEcb8nk9nnZlwSgSspGmVL4ynUGCffO90fEZ8S7iJYE6GJXS/mZDfx8rmwckmYE/18M+55FMDgZNnGcIgLxlH90ls4UxqtvpiTkTpjRf1Fe7OlzTrSJc5ic524ZWjpdJRalP5GnlEp3WP3j4Fzq0RbCRU9ph1GOGSAdLn1TIJ6h1HoTvFvZPewsxiMDNY83HF56S0nIIicINtuga7y5M1rft+JuP7Y6/jA6cS2kKyDWAQ88WALbNY/ObyA037jkfF8Ob9xlLuOtHvxH05Aocv5QxlMphKf1RVqK27DtU8r7gF9r1UODNDdyWnjg0BuuZMpHGq3NAMW1svO5AJAgVSQvaRJfqxIuMAMM6WzB9WqP+L6JKohnxXMC9+5l4jIGVdCPFbPUa3GwILZiGyXbzmIs1mc6aHHLWdzc7CzQkyg4xpEAo9bkPh0LFgr0riLDfEVN3Q+aA8QIMTF7xLSBiyaZ2uu94PAbeRvwTh1iIFg4xNBpsxo12hkNYA=
  template:
    metadata:
      name: immich-key
      namespace: homepage
