---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-key
  namespace: homepage
spec:
  encryptedData:
    apikey: AgA2IauI4F5/4cqyPIZA2eDMlOKh3ti6Bt7JcJpkQGJ+0aAefo6Dr9H+BliiyY2r1AcHQ179PSojbUcr9faEV322wMkYEMM929qNb9RmBugg7t6lob1+728Fs78w0qJwhKxk+FlUqfB+gPIsriyAoydrgUbRSCjc+KkaH/Fsx80HueyVTAcYoOKJEvxV0JxTrqwq59+YAnFh3snj2CwfmbfqBvVZV4JbpygIEdJvAfqExS+vp/S90z2MdV3lol7STRZNNRIuDhAGMssxTp+4N3vrBiS1S9v7e+5cnQSxHMvWFHCF7f3S0PEvfzGKwt4NyUCJ8Z0uYIVtD7Z3bmzVbqJdCBcSA8a4IFycpPZDpEHY7KjlsCNe83uATDzDDpRQLt/cyiPSrQir4fRXdmQmi1SE/oH1l4ULTuuSJE0oZUfoBX0tVopxfJ6+27C96Z0qDu36jL3cjaKSb4mtqVtmVGVRUiNcYSrp5sumXG6nkIyNEjnpLrv85BjxRXwPFWa2b3ffxArfiFVb2xZr5gktxfmQwuPva7wQukBVpffGXLCVa8U2KfJ3krkTjAqX81hfUwenFfdbZME5tgsNGNmcaTBOtoEsGDsZJDvK2R42Oy5/E24MWs7DCSbS6+KigmFH0vi12+RkQINZPC4W72D63Bmnci9CS17/V7nw8bp0uRxin2MBfMrdcsEJ6K5/W8Ss9t0EQn+piUME+Km8LmPG2b4kXiJr2NJ5fuEDYWtCHEngGv3STRsqriZ7gVc=
  template:
    metadata:
      name: immich-key
      namespace: homepage
