---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie-key
  namespace: homepage
spec:
  encryptedData:
    token: AgCmOH45pxaiVlxPcf6G7G9uxLT0iZTj58qVtZklsSTUtps4W5VOFNVqG6VxIHVdam+LWvQHNeDWPZ9tzUGDLnG3I8ZzkiLY/0ggHW7ozSYrZxiQ7y7kPMK7BzyZYQ095cIXrEocGvDfNXAnRU2XOMJNlQhDRhKKix/uOV074z2g11Nmr7XiQyTXfY/Os/sj1fzDr+HCekct56kMZcwcDZI41tYZ1g/IPHQr6B/fxiTJiMaSj92lXcbD6n9lszYcpiOvk8ZvqS6zLJetd5GMDWhVW9t7dtOQkYtkWBGb7ZldBeLQUigYVDlqAMAzOQZUPV3Yqbz0PKLIuI9bWN7CmlDTAHVHVRCAVG17FKmf8VhLcWBBjpyGKiiwnf3cE/SOB7kWTE2+jCHEr/IfnNQvkPqcE5PdWQzGYpydBpsm4oQ13z8zR6Taxag2GPojDO2b7ElR+crpPeKzW9r/4rWdKReMLGRw1Kw7yPVOis0bdBp+2/T8szt9GXj0Iez6lrhPXxsVEDf2oLdZBVZwiWnQGo+6xuYyS5PhlnAjldoJW1jzRFfH0RpImloks6BmC1rkpf1qwbwNmzQ4NKMpZsEu09yuSriCXRSkgoz30IzVjuui18XQhXrvPLNAKZrbGmsCC2kLsqXtRYBUHW7kedE0zPCfwVZMPv/madctip4NoAGIe6L5+rEA+/hXB1JlQEuPDBYX6u6waD5snCpQVv0955lJYQJar+A6hg3gU/zFMsuAbu7NJYuZr1aMW2GPGrOBpRdZYiL/eCy3/joOC9sY+HMQdZ0SHaFJvB+e620YwvRSuH3eP2WNlrtPGV/oMETY48Q5v2Q3Gb13gkYbULKWsjDWL0q8kLEaSjVt5tI3hb52vIBrL33iDIlIALJrg5etwzoYM+J0/FfvWnWnsBvvjFEwqO4zcNFRRsKKKYE4BEGvHffLOmnVOIGeDlfHa+PCCs20zzJSd1c3vq04mUlHjOY6/PrH6SFwLFgCj/ru/8v+wPiCrgKpS/WBlto2OALqnKmvUl6ge8T4uygvpv+5TrPW
  template:
    metadata:
      name: mealie-key
      namespace: homepage
