---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-key
  namespace: default
spec:
  encryptedData:
    password: AgCIGbhfuyFKTebacX5Vl9MZfeYvxuj2EEH+ScknWrrCzIp/Rduw4xzE/UqLt7f5UVepPEO/fRfrT4wj5EBy/k5WO5MgUQkhz/EJM8QcGO3ncR/gf9crUgrD5FT5CvfqXFydiNmTyVrOCuAPI2HbXEBZV5UToa4RDvNMO1GpTunXPPiEB5bTFxAuzN55fxk6GLs7/99zqo/oVVTre2ApvUZoxHJSpMX6jHJXABEm9QoCqTlAA1QYB7+WIggDIpxBQ6zOpGboD7Tk5K+im9UJo0lJjNychFc38SYOwmXtCcX5EaD+EOcK+MNNHjeBcykCwgc6rQ7GyP/+/dc5az0gaQVbRhbIbusnFbWKrM31tupX7JrB+463A0tazgjoRLyS8JwfhiZR8nh5WUpKxjGtV26T6HS8NPa2MFNC2tVlZbuaGW9PcIaM+5dvGZYmwjU1P6ekg+zt6MuRsjfWH+GBqxjpo+YXYDrru+5BXzOXyhFQaSu/nebwEx2JvHz30R8ByHQzwd+hf2o3op7sx6LKl3UeeYLv0vNjXwLVsYcNbiVXCXC97kBwf+TErZWTlsqlRdOxOFHmEN6qHVX7M8sUfqcH5r/Ui+9YTm7PSJSCtefUkif2TUiXJexwu1m0QhQZKE18MjU4hfLEPzwNSrhAvoXZsnUvQnHD1+3n/uzE1wiicLPbfVcHtAgNCLW4VY+Si4kWwrpGWW/kziR76GDQIHRTc3p5
    username: AgA4WCv6++TW0n+pQaW+6LAr6HNfg4pfGOSwCMG1D6IRR8NA4LFapEGNWr9LdfOXY7uG0qgoiUwKuE4xE1QyU5Na5ybaX8wGzsjdgnutxGtxq/6ASpkeDXdqlQHz5JXN8kurHmI0SBTfHKpDjZoQGRY9LzOTVk4E0bIARGBy9g422B0BuVylR3xWi8K+hBUZ9N4DCRX7pHj+N+87NQ5e9vPC7sN00S3BPpJGMCs+ziW/BhowaVY8UQhxvXwR/98aaYIpPXqeKyOSjxixCFyjimMY6XkoT91wQU28qGkL1OhxLTZ8/h7lRHQWUnRk7NORKcVTnLcXJQMj+vfEuY1jEZ5KqUEAhKwXU7GXN0vYPS2U1XsWDDs2vCs15aniXgPX2M8Dm9cca3ABbJP8tBU+CQzHWePDXc+s6vdjMk92kzAWPQzSQR4JvGrvA+TmcqhCdgGojNdb9UEKrX86dvufldHJ3NY4gbIp8KXe4eUJB57DsBT/dngQ/vpnUp3FWv10fd/gks31e6v6uLh7w3iXtok62jVy77YX4ldLogKxhzrFYo7nE7/WZ3+rLeOcH+3AUbNUa/61iEkODM8WolNUMQJsgGaCQbBFjgnfwt0ZRTn0bdt3mDV/xwuk0szzRf8GwROHq3GU8PA/XFhwP1ao60ueqGE3Uh3Xl21etNaliVYcGSBevVC65WyUD5W6+rYXXaL56qYkO+lBaDyFUlzf
  template:
    metadata:
      name: nextcloud-key
      namespace: default
