---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-key
  namespace: homepage
spec:
  encryptedData:
    password: AgAnq5JG2jehLeg/b7NaOXsX+559Mm1q/SRII+oTB+3lrm/sK4msuwfQHzximzBa1YpmmbPAt1C13Aqma6wysFteWnYESC0tO5HIR2Wnzi6n8zH+e9SxBYvtTJZgGwn29jLmgkkvWDC0iI9q/U+mns5gHX6rH5t3jpUJj6Jf2lD8aSrJsx2hHL2jptJ0xWgUsZNnKMlom02mDvl6XkpPeWrwQL8NStl+ivJdEddNemIVZc6AiAj+l5PuR88R2x0YhyvCm7bLp6rkRn3a6jiAcvnYdhDJXI6x2EsMNtO7rOXKnkolCDaPqr0lHSCjtmnWL6nI7VS40DfHGGFMAitOKYwpJGrQk3D6KGT2Xvh4PC6jVaLVKSQU1/SCKYV8x+b27xMw/BIM94utMPgiWMh3mxD0APqUH6BpF79bJDKo+O9JjGDOGA1uwhq3D7ZWHa+7ATWlsuIDZEjfbjdwjJC4bYc1cWULL+w2WbJ/ZgiHJsqtG9Row+o1yfoWgzvpeiEtnr/QI9Et1xr9tjeonb8d9SGhypLVweVmvo5uF2pIS/RjlOoY+FBfWASyiwVDD1Nb/nl6vtH+L+iIgh51RXgbVoAT/e/rWD+l+Cg22gOfXp3DlGweW0fOFj09pEqe2LNArQFigau+/XsEYvSlO/5l2EHgbtxFk2x9ZDLI3x2HwxGAK6cbCQ97ESAuPKflfjnCYqDbHhSGatSLBpi0bTSnFq5t8WAK
    username: AgB8C2bzAoF8F5umY4CpVD4qWCO3lh5mj/ZRK4Qn13nY3BLZDtftiLU5gKG6nBu5mRmpVcNoF8r0L+FB28nMjuG4EtaMIUbbsN707h3tKNNjKmVXgpHD4/KYg8pxv2C2lGF33qU02k8P+So+e7y1hpt+9ME/73Qz7Hg3Q71f89PC5llRAdrj9Dp96MeihbUrfDYvzmkSqwPrQWzUE8l4bM6vfP0/iDyoiuJBNgZad90hS5VYAa0ZFuXkM2W6XR+lDCO/hpsN38MrnwN3IxNGcligTC7ubeoWxAPUv78VUyOj1dsj4DPjRBivGsnAMm4JHV0pMtyslpa2E0fh3GybeKSA/oEQ4jNYluM57+TFiaCH0n6D1bnmVi1vniSvAEFY/QyS2vAxWxuMRxmiUZah0exI+0I6LptYsb4ArX+RN86GKB8WXCqChf6w1wOVDBu/fvxkOruQlcAilJ2An1cZV8bKLNByhzwfAfw3XfUDT/JuW9R7lzNPC0JnSOw4dEVcKl1+yTI8ftSFG/odxS3jInfPKd70JO4zrUGSnoJdx7QzBniMuHKC85SwWVe20sGNXICVZhTKoXUiENOcj/eRTuga79m2slz4nBuBdYjW0OdLEmms/TWHwGTMXY9MkcOHA4DbLZWlhU5C5tpn20Q8u5p+Df3YDLYgvT1wT2vuRDALdpD+IP3lfgIY95E2hKKPT3vTY0hOeuUWGkDvmccg
  template:
    metadata:
      name: nextcloud-key
      namespace: homepage
