---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-key
  namespace: homepage
spec:
  encryptedData:
    password: AgB088QCn5DSPlElKyGAjXojjomEPRJeHc1w/oEmgc50Qu5Lppr39dLkYAya7LOjCJ2aLaDI40bXmxdlMmt0w9PYWvsoEotwexG0mw67yh0yyFR7h6RgMJu/xceMu23c2gVnIt2pE79J7RRlcKAEtsAwawv0LyS6KnBtjodD6tJeCj4XxuCbNzUiTCA6atikMDYLu3Aj2jcMT6aX00Bh5P4O8LO6kHmLmsVMmOILXO4Q/hUsle4wiBTdIcLZCk3ykIlFW1tX0F3cPwFoWcP0dcFYuA5+VujIDgK4Gm+AmtAhu6AkpBoVoFtdGR9UBCtd3hbvsXB6U2lljLIhq7Nrlep0vB3QV4MrwFnW7Z46AlOV/Io4mGZj2s4zHww//k41UpsvMSxgyyb24+aAX/bHuOh6ByFc9V9B5bYiFfrSHHryHkyjjTjk9+BicAOzMyqfUsX1i3X0ihnmZH+JhBk974l+xR8efEwJMfJFYlPmOKLK7/b9M4RSZeaO9UrayRdAVfwVevt6iKHg28Mge1RjyggzFpsljpo6+z9M8O5fDVzGh1OqwsVYYX6CTUbQJdcm4GRkmDcnOG5ZLy8X0Ns4O6SPCskU9nJ2Jgx+HXcwyKCtACkFFg9aFzSt1OcuwurtbNUIaugRZdAK1p6qmaPLi9QPgZlDUyQT3kvfpWBcMhWNFbx5CForVICP+gTT5Hn5vkjsDZPJZKPWBS1ipDTuVVHszsnl
    username: AgBxBOFabRyB76SeNUzWUx9mXJomtcyta4JKxHH6RovVGzWq9RldXEIVObSAJirExpWty2IJ0gehSrJUiBjdJdjD/l+QFnmJ/VFa0pAei6GlGqKTq8fkTYhIdlAYJpBOBnHLuzwAU/DGRD4e/RLq6ofUgg2C9jJf8ssBQnxCJMsPTBAVtDbi/m2B2AfcJ1U3mbfEAweE2ISYIpZggGXy7R6EbGRskrArgKjuAPqjWXWhRyA4rKlUbkltRyOGw1AX4HTn1N2dhrdAk0tewZXIG0Sz50gFxm4H2EOVMEwkn/AcibotbWU+8BTIzfqskUpDZeHVk01CIuZsq1C6C785KmJyeMNzi+aLJrV2+hAoSXAVV0XA1kUaRM0lXGzaV0eg4zkULjmJ0VpmvwmLvRlxltNNVEnm1yVMcHUMb+F0aPIL1XnBmqlFsCZlA+lJJ91lOIm2mBnOfbmUuwK4yPyWMd49LLb2NsSOENJ8QbiU3y991IHf4vwc6pLArZHv0Hpuy5+FVElqIj9D5kmjFgvY5Ghl9qLOhK3bTjuHa1D2sR138BICYezypdnYdgyUkMASS25YcxUiT5QTr14ilLhNXEwx/W36eZaHhp4UHwcpX0yCEQmHxmFYJInldpcljitPO2VqDNOofu/p1Sc7lqUy8T1ibtmZLPt476WkIaSvsSKR6wucaziKRW7qL4I6kd6NVlKb3pXI2p+bgNNxiPa9
  template:
    metadata:
      name: nextcloud-key
      namespace: homepage
