---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-key
  namespace: homepage
spec:
  encryptedData:
    webpassword: AgCGuuK3YkomssU1NGczNylvadd+MSvf0Rg93BOnZCS7Q1sIXiWjJdzXoZEAsWzhOCwSEGHkbPjTXoKsTDryFpzNFbXObzguAfk9k+Ne9BYfhuBIqBgetiD9xivShPNy7Kkra+s7jhb95yAvMD/MDct/BKRdv+HE5jHIxKxqG0yW1eWh1b9aJgM1ci7/BYbwKKs3jJ5jWJFBRFqgUhzKmw+6RkKCUPHYPKpEsyHHKkKi0Sd4noSTGcqYODSI5LxI7swOLiPGYmO6Sc/GExl4JtTQ0feH/0zj9QoTeC27giLwADoqRke/Br7RLb3nn2hVP2Sb2LdjHu1boT1XQOVrfMlDWK6AehoAzUNvyyZYKIG1BgyLOVc2i/yU7b7hmBUuY5VWAmEnYQnAqqOyZU56h4FAd4Lw/Qv5C0ORFeqq4lO6qTUsH6cmGVzayGtSDtyOjomJeljtBhX0gdKdYxnfE58YjhUSPjjWcu4ac8jJRAy59aGLHssgN+W+1OV+HEqE6hL0sPkbIpkOxTm5Lvla1/bJZJSmivJKItdJLfV6+NEAffJqa//eNLPBUFrCl6RgygYmHQ4X6p5oSAMES6tdeWrM4++3ZIR35fmxM6Z3mEKAWRyXvgE35rgZm9AwFpcfU0NknsfLbgPDTj5nx/V8EYre4LME4GwLmpQj3CkJaZDfj6RrVA6LnXECA9e9G61X+HnHwV+zFy1A34RlYw==
  template:
    metadata:
      name: pihole-key
      namespace: homepage
