apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-config
  namespace: dashy
data:
  conf.yml: |
    pageInfo:
      title: Home Dashboard
      description: Dashy running on Kubernetes

    appConfig:
      theme: colorful

    sections:
      - name: Quick Links
        items:
          - title: Google
            url: https://google.com
