apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashy-config-pvc
  namespace: dashy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: longhorn-ssd
