image:
  # Override to latest stable version
  tag: "4.3"

# Set name override
nameOverride: "dashy"
fullnameOverride: "dashy"

# Necessary to allow pod to start
podSecurityContext:
  fsGroup: 2000

# Necessary to enable interaction with pod FS
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# Make service accessible outside cluster
ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: dashy.lan
      paths:
        - path: /
          pathType: ImplementationSpecific

nodeSelector: {} # Might pin to nodes with higher compute later

affinity: {} # Not sure what to do with this yet

env:
  HOST: "" # Fix an "incorrect host" bug
  BASE_URL: "/"

static:
  # If set to true, configuration will be overwritten on every new releases.
  enabled: true

  # Customize config.yaml https://github.com/Lissy93/dashy/blob/master/docs/configuring.md for more information.
  configMapContent:
    conf: |-
      # Page meta info, like heading, footer text and nav links
      pageInfo:
        title: Dashy
        description: Welcome to your new dashboard!
        navLinks:
          - title: GitHub
            path: https://github.com/Lissy93/dashy
          - title: Documentation
            path: https://dashy.to/docs

      # Optional app settings and configuration
      appConfig:
        theme: colorful

      # Main content - An array of sections, each containing an array of items
      sections:
        - name: Getting Started
          icon: fas fa-rocket
          items:
            - title: Dashy Live
              description: Development a project management links for Dashy
              icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
              url: https://live.dashy.to/
              target: newtab
            - title: GitHub
              description: Source Code, Issues and Pull Requests
              url: https://github.com/lissy93/dashy
              icon: favicon
            - title: Docs
              description: Configuring & Usage Documentation
              provider: Dashy.to
              icon: far fa-book
              url: https://dashy.to/docs
            - title: Showcase
              description: See how others are using Dashy
              url: https://github.com/Lissy93/dashy/blob/master/docs/showcase.md
              icon: far fa-grin-hearts
            - title: Config Guide
              description: See full list of configuration options
              url: https://github.com/Lissy93/dashy/blob/master/docs/configuring.md
              icon: fas fa-wrench
            - title: Support
              description: Get help with Dashy, raise a bug, or get in contact
              url: https://github.com/Lissy93/dashy/blob/master/.github/SUPPORT.md
              icon: far fa-hands-helping
