global:
  clusterDomain: "cluster.lan"

deploymentMode: Monolithic

namespaceOverride: "monitoring"

loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 2
    path_prefix: /var/loki

  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules

  storage_config:
    tsdb_shipper:
      index_gateway_client:
        server_address: ""   # not used in monolithic mode
    filesystem:
      directory: /var/loki/chunks

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: longhorn-ssd
    size: 20Gi
  affinity: {}

ingester:
  enabled: false

querier:
  enabled: false

queryFrontend:
  enabled: false

queryScheduler:
  enabled: false

distributor:
  enabled: false

compactor:
  enabled: false

indexGateway:
  enabled: false

ruler:
  enabled: false

bloomGateway:
  enabled: false

bloomPlanner:
  enabled: false

bloomBuilder:
  enabled: false

patternIngester:
  enabled: false

write:
  replicas: 0

read:
  replicas: 0

backend:
  replicas: 0

gateway:
  enabled: false

chunksCache:
  enabled: false

resultsCache:
  enabled: false

minio:
  enabled: false

test:
  enabled: false

lokiCanary:
  enabled: false
