services:
  type: LoadBalancer
loadBalancerIP: 192.168.0.200
ingress:
  enabled: true
  hosts:
  - host: cloud.internal
    paths:
      - /
nextcloud:
  host: cloud.internal
  username: admin
  password: changeMe
