---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: homarr
spec:
  encryptedData:
    password: AgC/n1+644WqAKw+EpsczLjrRSudh+0Sz1mpoWVrEspeuyeS6OKdM2+1ZwY72RX4QNlIvawufkRNwNOXm/aVRxfAa2YBrJdTrCFZUaN2BDKp9BAo4aNmoCh7WFozWmT/hl8UmbbnE1EP7POP1dOl7LlI7Sf7O17Cv9ebK1T1dwbgW8hGtpmNDJw3MEdRR09xpbG7L4PId6OtPBi6vGCRE+fucEZSA/RzFp2gUBE3xhMeLT06IWX1GKT6YAHYSy5RsukI+mLgdTGFkWtWzmgBARl9Wp8LzUXzqieaF8s9gRuJO9OOwo2JPPr8HymMw8MmnJVugRAHhKFbLxgtG+DTA+PAxBbSrVHDRgmNIyUG2+X1wLry4W+ZCO2Z4M0VC+g337R+K6ii3u7ZRjZ2DPVv+UJv+qKfDFNCaMxF4nAPwoVPAC36UaLmNYU4oG6dW2auqDgkRnQSNdU+YtEpEogAXt7HIqyLCo0tcbOKd/sj8nXZnMP3CBaaZOaWcqGYJWOArUo9JpEI5FdthaHPQYKuZyAu5TugWJ3ybuwHX5u4QVA5h0z+qwIUzrFe+Ye80xaaOcMWJgOoTL5dOJ+yQc8xQw+4AHebdTsRWo72XfWoNAc15dQ2zsLiPQ1EixTH6hpw+XCMmSFnfk/GXLSi/HJfHf9q03qXMPND8ThOBMNhvs9ukpRzbRUP1lElNKT4HSd/tt1vgiXlw2Et1gJocGGLY/fuullh
    username: AgCgJWNKyyEXElizrLHiUSrkvX2rCrBsNOYTeHXuAocuEVoaChg7LiuBdDytqLV/0nD0/ShyvPMKxt/uXXwj/gU4P6BRpPmLnSQ1fiwY4AjTHcKdXYk86NvfrdDs5OE6Wjk74WO6q+xaPtAC/AulOtQ/sBQQL5cH0kliD22fZZNMZ/QGlwNl3RyvIACtYXsp+1+aXF+DzLI338Cvym7RKFrfdTeHwuVXCdOhhnnV9JQOFJdaqK7tsfw1i38CJNMd9yN74brzmDtkB8AyJdL+BNd8eh2DzdGLoVTJHvxSi7cyux/PA7FxtpaknZ8SkOQ7DvO6S/NwR50W06tfjmURByD62pYAVsntYuKQPjVMItfFkJ2Nfut/YpdipaxEUzY1u+pWFsxKvO2ODKoaPobzEHXaWa8eKADOhdZ5uqOuViP+IC5EFyE6usAgvHq4e1AweLJobzZM9n5Vv7dPX7FxN0i0SrTB+Q9D/vAIwh4fvi0WGqrZZ9x7wThrpImoO01pIv2TTtqMaGYSAr/DI6PufCe9AKbLfL1pLZuhKucEm3KMBFmOC/syaraL217m6DuagXyfnJXmaoux0lCjPhVdTREqker97kM2ScjP8mxzMgR3yCBWccTArKhTI5FOiXTdPqNSstuBKxC5S40irZY67tBNWwWQdqqL6bnU/yUR8UX0QpDM+vVxDyQZ9ucFsFVYIWT8NZ58q0w=
  template:
    metadata:
      name: db-secret
      namespace: homarr
