image:
  tag: "v1.61.1-beta.1"
env:
  TZ: "America/Chicago"
envSecrets:
  dbCredentials:
    existingSecret: "db-secret"
  dbEncryption:
    existingSecret: "db-encryption"
    key: "db-encryption-key"
service:
  type: ClusterIP
  ports:
    app:
      port: 7575
      targetPort: http
      protocol: TCP
  ipFamilyPolicy: SingleStack
  ipFamilies: []
ingress:
  enabled: true
  ingressClassName: "traefik"
  hosts:
    - host: homarr.lan
      paths:
      - path: /
  tls: []
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 128Mi
persistence:
  homarrDatabase:
    enabled: true
    name: "homarr-database"
    storageClassName: "longhorn-ssd"
    accessMode: "ReadWriteOnce"
    size: "50Mi"
    mountPath: "/appdata"
