apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: netbird-tls
  namespace: netbird
spec:
  secretName: netbird-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - netbird.mafmanhomelab.dedyn.io
