---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-secrets
  namespace: default
spec:
  encryptedData:
    authSecret: AgAa8ub2CBdZR5TMpM2pyQAyQu8LcoWHoMuRJLKtFY4O/n8uZ2WNn3eMWNUUYf+x5KBzhCV8wxGHHZTasYUgJoOa8SjWY2TZ7fs+ey51wqbJ3dyBIHfRW+ywzLw6bIsRaBzqYVgJsrFcl/WyYXOzV4gGSIyyXoKHAzNK7wQjpY77r3ppK1LMHiV64CSQJ3zeqLhH2MOEl0Re0u0PJCtRUHLeZRS3u/HjCmoTaP02elgsD8jcZeW7Q7kFbZ7lKiSTDkAifYJwi77LGSFEJksxzpKxeoh8kJp3K9lKVK759ozesjEe68uHa6C8d9vKAjeNnBqYCMN85oBGCgLD9A1sysfQFATnlAYDsmVYPKLlf6qyNYBsPvUIcaPo/o8xjw4WO3UuLZ9QRssTZfGr7nJ5qmOnysicv1zR005FmDjkOgxZDTI+A3W26fK+uNzmIvMwXGAKaQc4nP/1sjP9i3JnvQFn1EVl3DS2NuotYQ6abBS3MEjXOix2xi3pDu70U6KDNLyF7WhNFP+iLAlv5SAQfoLIL7G5sy2wCqi/f3MR6icbqAHh32ly3oBeGds7XsSZh7PmablE9IK1ODcIlmSAURUgk/BpvDobziunmCpmajRI532drZHHkUTtIbUx0ZCZHwDUJhdyfcZUuWT3fhdx7OKGgtoHzshAyXhP55lsVasNGRh3/E907LvjCPTuc6aXHu4p/Uv5t1m+IK+M/h8Wo0jU07EvUYFoFLbeNA==
    encryptionKey: AgA7LMNuWh3lLzwA6pJ9SIZ4CuFzBJFWnbLk0adnBOoJfska8ozaqgc+2HEIhgpAn8qbRxqVPvGWTBBEGrpDwxcpGHISNoReYX7a3P6S1LBfckS/JRyzzSuJeKiEK6N5e5P13DnUr7a700smeJJCO8iQMtSGbhVqzSNvD9q3MfJpfpjMT1umvgYXis5asaMjeIU8uQkrF5CV5N1zl51iYJMLQpT7CUGkBO1BqCU7Et1YQ+BOaDsWnVrG4Ico/vPybu622s84GuxlP2Jd4DrPKB6UE+PSdetSgAiQVBBnUlxMa9kOfgvVSbFBAcC0NH8iTagtUCXRUGReEziJmRcPehjRo1kNDpvZuhp5WR7BE5kua9UpIRGoKhAcsm2szryzUoLKt8aCFZu5d1cqeuOvvsqfJv8Kac+5ne1zOuUIivBzbS1ys9iFwf7TF2Jo74tHAMNV5qBBQJPUzBRe1TTw0b8qGlIAjy1EOh9ncY19Hv8Vz9/mk3plaJhuLANLpGYOFJoSiULIzHwMmAN/d077P4shtBZcYHwaWSICcNyWcd2TqEXPqFIg9QM7kO6jpFRp2qecr5EtmcRC2OXDS5aEcCN6qAbHtbljndLecUbBx92+a7aGjzsgh1mXPfCfQe812QkjfTt97drdxUqw3v3tuZW7F2W0fnQOsesj3mAOycxMjQyB7zvZHMe0Zo8itIzWWkxx692P1h/ifRpCueJvEoOw26gr81NFNODT
  template:
    metadata:
      name: netbird-secrets
      namespace: default
