apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: netbird-server
  name: netbird-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: netbird-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: netbird-server
    spec:
      containers:
        - args:
            - --config
            - /etc/netbird/config.yaml
          image: netbirdio/netbird-server:latest
          name: netbird-server
          ports:
            - containerPort: 3478
              protocol: UDP
          volumeMounts:
            - mountPath: /var/lib/netbird
              name: netbird-data
            - mountPath: /etc/netbird/config.yaml
              name: netbird-server-cm1
              subPath: config.yaml
          env:
          - name: NB_AUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: netbird-secrets
                key: authSecret
          - name: NB_STORE_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: netbird-secrets
                key: encryptionKey
      restartPolicy: Always
      volumes:
        - name: netbird-data
          persistentVolumeClaim:
            claimName: netbird-data
        - configMap:
            items:
              - key: config.yaml
                path: config.yaml
            name: netbird-server-cm1
          name: netbird-server-cm1
