apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: netbird-data
  name: netbird-data
  namespace: netbird
spec:
  storageClassName: longhorn-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
