---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-secret
  namespace: netbird
spec:
  encryptedData:
    encryption_key: AgCj3RjFVwpDTmlXvC3aYE5lH9Ge8cjb54rwHSQKOOOVq7eA64eAUL/Ji2tXMCvWM2sXetzUArk7JtnuRQMnv/X9pvosDjL7UXtEE2VzVlq42OQSLTiHRNgxkZueWRwduRGss/pfWYxBRNk4Cft8pfjGcOHtNxdOJAL/w4AcCJaStcbg2a2VQT5VhIIUyd/Cm+Z3Wsu3W3agkSz9NAFQ/2uAjGJtwervKJ/KuAgt2+NNsYqrXAlVO+o64kZ28ZcImpV9YR0JMrVh5vStdLzwDG5pgKRj5nmR/JmWdXI/MVfrEekot0zzQBvH5kC4LdV68/xLOEhMocoNrsf6bzcEmGBqSNSKLXpo55Vpd1IhnzDyQFKxaDRBZ3jGHY5xhpVxdJUcPrVDQx7whbfJomfGlb+Te422PVl9tNZwxVGpp0KoifTqNQwZmLdsPlF+aj7+htRR7WESHjqhD5gQ+izVpauwuTzwNjE5jOZCvCFlkZtIMWGfn4SdKQlb2tlC+iAVmaQgkeAbMDBc8kFyJL4NAnCXzzSwRVOOLUdjCk2XXOMo1hy5PfRr/JwJtbwThcqIGsVcPvIbkco5Yw+GFHkjRSbPMM/irXO0ntNq/pdeELgD/iweZg0sOnCcceRBYTVJBc6z0KLAfJdS84ky+5QNOUlfzXO7v5WoIAb/zvgM5ki3hxT280C5S4jNKNhV+4X+spvB8czT+2Sk3r5NFzcgCefLXfNv5BLQVPuO4g==
  template:
    metadata:
      name: netbird-secret
      namespace: netbird
