apiVersion: v1
data:
  mimir.yaml: |-
    target: all
    common:
      storage:
        backend: filesystem
    blocks_storage:
      filesystem:
        dir: /data/tsdb
    ruler_storage:
      filesystem:
        dir: /data/ruler
    alertmanager_storage:
      filesystem:
        dir: /data/alertmanager
    ingester:
      ring:
        kvstore:
          store: inmemory
kind: ConfigMap
metadata:
  labels:
    app: mimir
  name: mimir-config
  namespace: lgtm
