apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    app: mimir
  name: mimir
  namespace: lgtm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        app: mimir
    spec:
      nodeSelector:
        diskType: ssd
      containers:
        - args:
            - -config.file=/mimir/config/mimir.yaml
            - -target=all
          image: grafana/mimir:3.1.1
          name: mimir
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /mimir/config/mimir.yaml
              name: mimir-config
              subPath: mimir.yaml
            - mountPath: /data
              name: mimir-claim0
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: mimir.yaml
                path: mimir.yaml
            name: mimir-config
          name: mimir-config
        - name: mimir-claim0
          persistentVolumeClaim:
            claimName: mimir-claim0
