apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mimir-claim0
  name: mimir-claim0
  namespace: lgtm
spec:
  storageClassName: longhorn-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
