---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-webpassword
  namespace: pihole
spec:
  encryptedData:
    FTLCONF_webserver_api_password: AgBtuD3myKgNwDFyuPZFVGxQ44XrVo7zEtWS8/WlwLn4ny5lptpOBBk2+DfQ4MFILvn1CN072R1g8fBqlP3xG+ByWQQDE+NGpVwXKhcylvEBTC2lp+s/xiLfCOnt9r82jtBuFAAU8LzfVJgjVid4Rba8aEiJxg4bRCOSb5BOvzygZbvY1EUFejMIiUIHD9SSk6ZFghUTvR360mBzxj07dSJRkIFRbITXk7gpnB2sRjAAeWIHilorxqneztxbUsRJ9x9J/tChXhcnU3bAjqEM0BDyD6bu4l7mcoj6PTTg0lJYzQFTbHIhzYHDWcS35fxVgExR3/lDotQNxIJ6B0+UWTqvhvKlQ1MG6nPG7/F8YMddWsvV4PCZtipuVeNLwT54Ej2f/qYcWshGuyleTq+6VgQLiE9EUnDndCDkqWDNWNXCmWsiN1NG7SxXZOBd0RXWPuL44qn/7bOUhKPpmDtxqY2Gc3yZ+Bh/JPKRgbPo0J+o8z9zZxBbVT57CPDsNa/qjOcDixjPyXkziWINoSuNDEZ6vurVOpzdmFq6TjQX6uquIiiwBe+OEV5w0M35ePu77zNWen+VPBGs+eM4zc7/DgaR05eTlBk7DQqFW4BOCRbLxioOkPY5oPnh9cqw113Wv9NNRnnYT3R5dnzP75FMidt69et4hDggUYYHAfS6Tm50XcwkaOLoQ513c4o6XiJtvJp1V2j5E6vCj+KJ1w==
  template:
    metadata:
      name: pihole-webpassword
      namespace: pihole
