---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    FTLCONF_webserver_api_password: AgBI1wk02Upo6/R0BdNUGI+gZ+IK6U7qer92lPXhrjtP+/yNBcAw1vjH/yBa4Ah7iyjpCYCmL1pZkjV1csfJQg7zCySU8Qfr5xDQ/7xvmSBs9QKk5Lbfd8COB3k2S4jqFha8B27phNoeks0SWZS9OyIC8KoNZNY5CPuiNYa1I4PiKzb0CjUUBG1ad5HLNDD0a1hqqqoqXuKxNwrFVbFKBBCf9k3gBju2BtfFgREpWy4wbgJAQj5Y4a1TfouKvesAX+gncZTYc/FF28mmUn+jrQh6BrJjezJ8JlesAFt3ObCN4f7mqdCCHYDlc/nD5DJ1lI7bb+Wp2j52uzJbZObONqEXfmzrenxgSFWDDHR5EFt5+PjGNvxi+zjKK3GS3oIh3DCWE1keoloWeaNzvLhIoMA3SoC6qv9aMW8kzkGEHD8/eRidiLayV0IqluJGN+kijQVHXS3W0jHvhS5lINLyHWYRGMSCDa+L2dRa8MlBmERcuzO12683tkiQs2Q7GHhMaHdShkUjH0JZ3u7Ss1vK66P5syj9Clm0KxU/5F/3b1NfVm56pHc/BQTn52aMac2GxBicmv7Ry75E76v6FpkKJAbM3pBKQ621D1UU00gSm+gYpDCeOmfeQK+nPmwGUQb1YxHmOO+2kksZWusg8bQ8jQv5t/m+dLYLORH72J2Sw//b5vWkReI2z8xyXD8+4iUIjtos+TX94fOA0rPpZg==
  template:
    metadata:
      name: pihole-secret
      namespace: pihole
