---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    FTLCONF_webserver_api_password: AgA08YHJpnBhcYY4B4R7AsYg3MJCaHTFYgOCRgP+J6TvkjGju3GM6M1dW3DMOn6oc15G/Cco97gJlnTXvg1o8vuu8TipCnADTh5Dts84pvULE7TQkazAw45KwcTKWGh1hM5URbgrDxXiE3NRDAKWjSlBQJzm1PNxzHFl4u0jjylpUDYfiZdVRMu5elIzLUd7gjL7Q9+2MsqXZtDiND1wcYQlv9goJehDlSBtoATg57P/M3jpm6Ymlcab+Fyhn8shHjMFtnQirDpgD5PMndaGsrfh13QmU5p0dkpO6G058jyJrIuei1xz+bU+0SZYxkZzxM0hKWbYdNxW7nlXRGdVpzDnNLZyOiSTTg4RXNjwjrHrJkzuS/jyRcX9Irey7sFQJYZ/ex/FhBXxgSMq8rPueA++t/xQBshZI+7QqokoRCZvNWFhaNxFczJB8a2xaKgfJ3RP6VRYISTNab/8TCQWl0TkQuJDNbTFABvyJOYFDGEgyEik+2L1JqG5dvXuFfgaxQGd8uc+Nbb6bwfUfsUm6KBT+v4hxjkwDBqRB1isGy3DOY4urlhKnC8ZF+XcLnFvzwEEj67zEQSfrlkLN/WhXU8qjxbcMg48kkPEk+S8GLwZZbeWbBT5gwgFShIR/JcKgRafTvZce0CpOtabXGlXf+bVMEJ6brq0Hcmf/3Xw2DmNFP+RJJasG223aAXCo/1ZSJtrgZVxKg9QwBh+Og==
  template:
    metadata:
      name: pihole-secret
      namespace: pihole
