apiVersion: v1
kind: Service
metadata:
    name: vaultwarden
    namespace: vaultwarden
    labels:
        app: vaultwarden
spec:
    ports:
    - name: "http"
      port: 8000
      targetPort: 80
    selector:
        matchLabels:
            app: vaultwarden
