server:
  retention: 7d
  retentionSize: "20GB"
  extraArgs:
    web.enable-remote-write-receiver: null

  persistentVolume:
    enabled: true
    storageClass: longhorn-ssd
    size: 20Gi

  resources:
    requests:
      cpu: 200m
      memory: 512Mi

alertmanager:
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: longhorn-ssd
    size: 2Gi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 50m
      memory: 50Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi

prometheus-pushgateway:
  enabled: false