apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: valkey-data
  name: valkey-data
  namespace: searxng
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
