services:
  db:
    image: postgres:16
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=joplin
      - POSTGRES_USER=joplin
      - POSTGRES_DB=joplin
    ports:
      - "5432:5432"
  app:
    image: joplin/server:latest
    environment:
      - APP_BASE_URL=joplin.internal
      - APP_PORT=22300
      - POSTGRES_DBPASSWORD=joplin
      - POSTGRES_DATABASE=joplin
      - POSTGRES_USER=joplin
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - DB_CLIENT=pg
    restart: always
    ports:
      - "22300:22300"
    depends_on:
      - db
