apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: joplin
  namespace: joplin
  labels:
    app: joplin
  annotations:
    gethomepage.dev/description: Self-Hosted Notes
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: sh-joplin
    gethomepage.dev/name: Joplin
    gethomepage.dev/href: http://joplin.internal/home/
    gethomepage.dev/siteMonitor: http://app.joplin.svc.cluster.local:22300
spec:
  rules:
    - host: "joplin.internal"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 22300
