apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim0
  namespace: joplin
  labels:
    app: db-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
