# This is the PVC for the actual images in Immich. It does need to be pretty big depending on upload volume.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-database
  namespace: immich
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 47Gi # 50 gigabytes = 46.56613 gibibytes

---
# This is the PVC for the ML model
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-machine-learning
  namespace: immich
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
