tempo:
  replicationFactor: 1
  
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 1000m

  retention: 336h   # 14 days

persistence:
  enabled: true
  storageClassName: longhorn-ssd
  accessModes:
    - ReadWriteOnce
  size: 20Gi

tempoQuery:
  enabled: false

service:
  type: ClusterIP

traces:
  otlp:
    grpc:
      enabled: true    # port 4317
    http:
      enabled: true    # port 4318
  jaeger:
    thriftHttp:
      enabled: true    # port 14268
    grpc:
      enabled: true    # port 14250
  zipkin:
    enabled: false
